//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottishGlen
{
    using System;
    using System.Collections.Generic;
    
    public partial class scottishGlenSoftware
    {
        public int id { get; set; }
        public string operatingSystemName { get; set; }
        public string version { get; set; }
        public string manufacturer { get; set; }
        public string hardwareName { get; set; }
    }
}
